#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace TechCosmos.SkillSystem.Editor
{
    /// <summary>
    /// 技能 / Buff 共用枚举文件的读写。
    /// </summary>
    public static class SkillSystemEnumGenerator
    {
        private const string GeneratedRegionStart = "// BEGIN_AUTO_GENERATED";
        private const string GeneratedRegionEnd = "// END_AUTO_GENERATED";

        public static List<string> LoadEnumValues(SkillSystemEnumKind kind)
        {
            var def = SkillSystemEnumCatalog.Get(kind);
            var path = ResolveExistingFilePath(kind, def.FilePath);
            if (path == null)
                return new List<string>(def.DefaultValues);

            if (kind == SkillSystemEnumKind.TriggerEvent)
            {
                var values = LoadAllEnumValuesFromFile(path);
                var legacyActionPath = "Assets/Generated/SkillSystem/BuffActionType.cs";
                if (File.Exists(legacyActionPath))
                {
                    foreach (var legacy in LoadAllEnumValuesFromFile(legacyActionPath))
                    {
                        if (!values.Contains(legacy))
                            values.Add(legacy);
                    }
                }
                return values;
            }

            return LoadAllEnumValuesFromFile(path);
        }

        private static string ResolveExistingFilePath(SkillSystemEnumKind kind, string primaryPath)
        {
            if (File.Exists(primaryPath))
                return primaryPath;

            var legacyPath = kind switch
            {
                SkillSystemEnumKind.BuffModifyType => "Assets/Generated/SkillSystem/BuffModifyType.cs",
                SkillSystemEnumKind.BuffTag => "Assets/Generated/SkillSystem/BuffTag.cs",
                SkillSystemEnumKind.TriggerEvent => "Assets/Generated/SkillSystem/BuffActionType.cs",
                _ => null
            };

            if (!string.IsNullOrEmpty(legacyPath) && File.Exists(legacyPath))
                return legacyPath;

            return null;
        }

        public static void WriteEnum(SkillSystemEnumKind kind, IEnumerable<string> values)
        {
            if (kind == SkillSystemEnumKind.TriggerEvent)
            {
                TriggerEventEnumGenerator.WriteExplicitEvents(values);
                return;
            }

            WriteSimpleEnum(kind, values);
        }

        public static void WriteSimpleEnum(SkillSystemEnumKind kind, IEnumerable<string> values)
        {
            var def = SkillSystemEnumCatalog.Get(kind);
            var items = new HashSet<string>();
            foreach (var value in values ?? Array.Empty<string>())
            {
                if (!string.IsNullOrWhiteSpace(value) && value != "None")
                    items.Add(SanitizeName(value));
            }

            if (items.Count == 0)
            {
                foreach (var fallback in def.DefaultValues)
                    items.Add(fallback);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"// 生成时间: {DateTime.Now:yyyy/MM/dd HH:mm:ss}");
            sb.AppendLine("// 由 Skill System Enum Editor 维护");
            sb.AppendLine("// 更新方式: Tech-Cosmos → SkillSystem → Enum Editor");
            sb.AppendLine();
            sb.AppendLine("namespace TechCosmos.SkillSystem.Runtime");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {def.EnumTypeName}");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");
            sb.AppendLine();

            int index = 1;
            foreach (var item in items.OrderBy(v => v))
            {
                sb.AppendLine($"        {item} = {index},");
                index++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(def.FilePath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(def.FilePath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();
            Debug.Log($"✅ {def.EnumTypeName} 已生成到 {def.FilePath}，共 {items.Count} 项");
        }

        public static Type ResolveRuntimeEnumType(SkillSystemEnumKind kind)
        {
            var def = SkillSystemEnumCatalog.Get(kind);
            foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
            {
                var type = asm.GetType($"TechCosmos.SkillSystem.Runtime.{def.EnumTypeName}");
                if (type != null && type.IsEnum)
                    return type;
            }
            return null;
        }

        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
            "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
            "using", "virtual", "void", "volatile", "while"
        };

        public static string SanitizeName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return "Unnamed";
            name = name.Trim().Replace(" ", "_");
            if (!char.IsLetter(name[0]) && name[0] != '_')
                name = "_" + name;
            name = Regex.Replace(name, @"[^\w]", "");
            return string.IsNullOrEmpty(name) ? "Unnamed" : name;
        }

        public static bool IsValidEnumMemberName(string name)
        {
            if (string.IsNullOrWhiteSpace(name) || name == "None")
                return false;
            if (CSharpKeywords.Contains(name))
                return false;
            return Regex.IsMatch(name, @"^[a-zA-Z_]\w*$");
        }

        public static bool TryNormalizeEnumMemberName(string rawName, out string memberName)
        {
            memberName = SanitizeName(rawName);
            if (!IsValidEnumMemberName(memberName))
            {
                memberName = null;
                return false;
            }

            return true;
        }

        private static List<string> LoadSimpleEnumValuesFromFile(string path)
        {
            return LoadAllEnumValuesFromFile(path);
        }

        private static List<string> LoadAllEnumValuesFromFile(string path)
        {
            var values = new List<string>();
            foreach (var line in File.ReadAllLines(path))
            {
                if (!TryParseEnumMemberLine(line, out var memberName))
                    continue;
                if (IsValidEnumMemberName(memberName))
                    values.Add(memberName);
            }

            return values;
        }

        internal static bool TryParseEnumMemberLine(string line, out string memberName)
        {
            memberName = null;
            var trimmed = line.Trim();
            if (trimmed.StartsWith("//") || string.IsNullOrWhiteSpace(trimmed))
                return false;
            if (trimmed.Contains("namespace") || trimmed.Contains("public enum") || trimmed.Contains("public static class"))
                return false;
            if (trimmed == "{" || trimmed == "}")
                return false;
            if (trimmed.StartsWith("// BEGIN_") || trimmed.StartsWith("// END_"))
                return false;

            var match = Regex.Match(trimmed, @"^(\w+)\s*(?:=\s*\d+\s*)?,?\s*$");
            if (!match.Success || match.Groups[1].Value == "None")
                return false;

            memberName = match.Groups[1].Value;
            return true;
        }
    }
}
#endif
