// Editor/TriggerEventEnumGenerator.cs
#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using TechCosmos.SkillSystem.Runtime;

namespace TechCosmos.SkillSystem.Editor
{
    public static class TriggerEventEnumGenerator
    {
        private const string ENUM_FILE_PATH = "Assets/Generated/TriggerEventType.cs";
        private const string GENERATED_REGION_START = "// BEGIN_AUTO_GENERATED";
        private const string GENERATED_REGION_END = "// END_AUTO_GENERATED";

        /// <summary>
        /// 从所有 IUnit 实现的 GetSupportedEvents() 收集事件，生成枚举
        /// </summary>
        public static void UpdateTriggerEventEnum()
        {
            var events = CollectAllEvents();

            // 保留已有枚举中不在自动生成区域的值
            var existingManualValues = ParseExistingManualValues();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// 由代码生成器自动维护，请勿手动修改自动生成区域");
            sb.AppendLine("// 更新方式: Tech-Cosmos → SkillSystem → Generator → Update TriggerEvent Enum");
            sb.AppendLine();
            sb.AppendLine("namespace TechCosmos.SkillSystem.Runtime");
            sb.AppendLine("{");
            sb.AppendLine("    public enum TriggerEventType");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");
            sb.AppendLine();

            // 手动定义的
            foreach (var manual in existingManualValues)
            {
                sb.AppendLine($"        {manual},");
            }

            if (existingManualValues.Count > 0)
                sb.AppendLine();

            sb.AppendLine($"        {GENERATED_REGION_START}");

            int index = 100; // 从 100 开始，避免冲突
            foreach (var evt in events.OrderBy(e => e))
            {
                sb.AppendLine($"        {evt} = {index},");
                index++;
            }

            sb.AppendLine($"        {GENERATED_REGION_END}");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 扩展方法
            sb.AppendLine("    public static class TriggerEventTypeExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static string ToEventString(this TriggerEventType type)");
            sb.AppendLine("        {");
            sb.AppendLine("            return type.ToString();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static TriggerEventType FromString(string eventString)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (System.Enum.TryParse<TriggerEventType>(eventString, out var result))");
            sb.AppendLine("                return result;");
            sb.AppendLine("            return TriggerEventType.None;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 确保目录存在
            var dir = Path.GetDirectoryName(ENUM_FILE_PATH);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(ENUM_FILE_PATH, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            Debug.Log($"✅ TriggerEventType 枚举已更新，共 {events.Count} 个事件");
        }

        /// <summary>
        /// 收集所有事件字符串
        /// </summary>
        private static HashSet<string> CollectAllEvents()
        {
            var events = new HashSet<string>();

            var allAssemblies = AppDomain.CurrentDomain.GetAssemblies()
                .Where(a => !a.IsDynamic);

            foreach (var assembly in allAssemblies)
            {
                try
                {
                    var types = assembly.GetTypes()
                        .Where(t => t.IsClass && !t.IsAbstract)
                        .Where(t => typeof(IUnit<>).MakeGenericType(t).IsAssignableFrom(t) ||
                                    t.GetInterfaces().Any(i => i.IsGenericType &&
                                        i.GetGenericTypeDefinition() == typeof(IUnit<>)));

                    foreach (var type in types)
                    {
                        try
                        {
                            // 尝试创建实例调用 GetSupportedEvents
                            var unitInterface = type.GetInterfaces()
                                .FirstOrDefault(i => i.IsGenericType &&
                                    i.GetGenericTypeDefinition() == typeof(IUnit<>));

                            if (unitInterface == null) continue;

                            // 用反射调用 GetSupportedEvents
                            var method = type.GetMethod("GetSupportedEvents",
                                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);

                            if (method == null)
                            {
                                // 检查接口隐式实现
                                var interfaceMap = type.GetInterfaceMap(unitInterface);
                                var index = Array.IndexOf(interfaceMap.InterfaceMethods,
                                    unitInterface.GetMethod("GetSupportedEvents"));
                                if (index >= 0)
                                    method = interfaceMap.TargetMethods[index];
                            }

                            if (method != null)
                            {
                                try
                                {
                                    var instance = Activator.CreateInstance(type);
                                    if (method.Invoke(instance, null) is string[] eventStrings)
                                    {
                                        foreach (var evt in eventStrings)
                                            events.Add(evt);
                                    }
                                }
                                catch
                                {
                                    // MonoBehaviour 不能随便实例化，跳过
                                }
                            }
                        }
                        catch { }
                    }
                }
                catch { }
            }

            // 也扫描 SkillDataSO 子类中的 TriggerEvent 字段默认值
            foreach (var assembly in allAssemblies)
            {
                try
                {
                    var soTypes = assembly.GetTypes()
                        .Where(t => t.IsClass && !t.IsAbstract &&
                                    t.IsSubclassOf(typeof(SkillDataSO)));

                    foreach (var type in soTypes)
                    {
                        var field = type.GetField("TriggerEvent",
                            BindingFlags.Public | BindingFlags.Instance);
                        if (field == null) continue;

                        // 检查是否有 DefaultValue 或初始化值
                        var fieldInfo = type.GetProperty("TriggerEvent",
                            BindingFlags.Public | BindingFlags.Instance);
                        // 这个很难静态获取，跳过用下面的方式
                    }
                }
                catch { }
            }

            return events;
        }

        private static List<string> ParseExistingManualValues()
        {
            var manual = new List<string>();
            if (!File.Exists(ENUM_FILE_PATH)) return manual;

            var lines = File.ReadAllLines(ENUM_FILE_PATH);
            bool inGenerated = false;

            foreach (var line in lines)
            {
                if (line.Contains(GENERATED_REGION_END))
                {
                    inGenerated = false;
                    continue;
                }
                if (line.Contains(GENERATED_REGION_START))
                {
                    inGenerated = true;
                    continue;
                }
                if (inGenerated) continue;

                var trimmed = line.Trim();
                if (trimmed.StartsWith("//") || string.IsNullOrWhiteSpace(trimmed)) continue;
                if (trimmed == "{" || trimmed == "}" || trimmed.StartsWith("namespace")) continue;

                // 提取枚举值名
                var match = System.Text.RegularExpressions.Regex.Match(trimmed, @"^(\w+)");
                if (match.Success && match.Groups[1].Value != "None" && match.Groups[1].Value != "public" && match.Groups[1].Value != "enum")
                {
                    manual.Add(match.Groups[1].Value);
                }
            }

            return manual;
        }
    }
}
#endif