// Editor/TriggerEventEnumGenerator.cs
#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Reflection;
using UnityEditor;
using UnityEngine;
using TechCosmos.SkillSystem.Runtime;

namespace TechCosmos.SkillSystem.Editor
{
    /// <summary>
    /// 从 IUnit 与 SkillDataSO 资产收集触发事件，自动生成 TriggerEventType 枚举。
    /// </summary>
    public static class TriggerEventEnumGenerator
    {
        private const string ENUM_FILE_PATH = "Assets/Generated/TriggerEventType.cs";
        private const string GENERATED_REGION_START = "// BEGIN_AUTO_GENERATED";
        private const string GENERATED_REGION_END = "// END_AUTO_GENERATED";

        /// <summary>收集所有触发事件并写入 TriggerEventType.cs。</summary>
        public static void UpdateTriggerEventEnum()
        {
            var events = CollectAllEvents();

            foreach (var existing in ParseExistingGeneratedValues())
                events.Add(existing);

            var existingManualValues = ParseExistingManualValues();

            if (events.Count == 0)
            {
                events.Add("OnAttack");
                events.Add("OnDamaged");
                events.Add("OnHeal");
            }

            WriteEnumFile(events, existingManualValues);
        }

        /// <summary>由 TriggerEvent 枚举编辑器写入事件列表（与自动生成器共用格式）。</summary>
        public static void WriteExplicitEvents(IEnumerable<string> eventNames)
        {
            var events = new HashSet<string>();
            foreach (var name in eventNames ?? Array.Empty<string>())
            {
                if (!string.IsNullOrWhiteSpace(name) && name != "None")
                    events.Add(name);
            }

            foreach (var collected in CollectAllEvents())
                events.Add(collected);

            if (events.Count == 0)
            {
                events.Add("OnAttack");
                events.Add("OnDamaged");
                events.Add("OnHeal");
            }

            WriteEnumFile(events, new List<string>());
        }

        private static void WriteEnumFile(HashSet<string> events, List<string> existingManualValues)
        {
            var validManual = new List<string>();
            foreach (var manual in existingManualValues)
            {
                if (SkillSystemEnumGenerator.IsValidEnumMemberName(manual))
                    validManual.Add(manual);
            }

            var validEvents = new HashSet<string>();
            foreach (var evt in events)
            {
                if (SkillSystemEnumGenerator.TryNormalizeEnumMemberName(evt, out var memberName))
                    validEvents.Add(memberName);
                else if (!string.IsNullOrWhiteSpace(evt))
                    Debug.LogWarning($"[TriggerEventEnumGenerator] 跳过无效事件名 '{evt}'（非合法 C# 标识符或为保留字）");
            }

            foreach (var manual in validManual)
                validEvents.Remove(manual);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// 由代码生成器自动维护，请勿手动修改自动生成区域");
            sb.AppendLine("// 更新方式: Tech-Cosmos → SkillSystem → Enum Editor");
            sb.AppendLine();
            sb.AppendLine("namespace TechCosmos.SkillSystem.Runtime");
            sb.AppendLine("{");
            sb.AppendLine("    public enum TriggerEventType");
            sb.AppendLine("    {");
            sb.AppendLine("        None = 0,");
            sb.AppendLine();

            foreach (var manual in validManual)
            {
                sb.AppendLine($"        {manual},");
            }

            if (validManual.Count > 0)
                sb.AppendLine();

            sb.AppendLine($"        {GENERATED_REGION_START}");

            int index = 100;
            foreach (var evt in validEvents.OrderBy(e => e))
            {
                sb.AppendLine($"        {evt} = {index},");
                index++;
            }

            sb.AppendLine($"        {GENERATED_REGION_END}");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public static class TriggerEventTypeExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static string ToEventString(this TriggerEventType type)");
            sb.AppendLine("        {");
            sb.AppendLine("            return type.ToString();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static TriggerEventType FromString(string eventString)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (System.Enum.TryParse<TriggerEventType>(eventString, out var result))");
            sb.AppendLine("                return result;");
            sb.AppendLine("            return TriggerEventType.None;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var dir = Path.GetDirectoryName(ENUM_FILE_PATH);
            if (!Directory.Exists(dir))
                Directory.CreateDirectory(dir);

            File.WriteAllText(ENUM_FILE_PATH, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            Debug.Log($"✅ TriggerEventType 枚举已更新，共 {validEvents.Count + validManual.Count} 个事件");
        }

        private static HashSet<string> CollectAllEvents()
        {
            var events = new HashSet<string>();

            var allAssemblies = AppDomain.CurrentDomain.GetAssemblies()
                .Where(a => !a.IsDynamic);

            foreach (var assembly in allAssemblies)
            {
                try
                {
                    var types = assembly.GetTypes()
                        .Where(t => t.IsClass && !t.IsAbstract)
                        .Where(t => t.GetInterfaces().Any(i => i.IsGenericType &&
                            i.GetGenericTypeDefinition() == typeof(IUnit<>)));

                    foreach (var type in types)
                    {
                        try
                        {
                            var unitInterface = type.GetInterfaces()
                                .FirstOrDefault(i => i.IsGenericType &&
                                    i.GetGenericTypeDefinition() == typeof(IUnit<>));

                            if (unitInterface == null) continue;

                            var method = type.GetMethod("GetSupportedEvents",
                                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);

                            if (method == null || method.DeclaringType != type)
                            {
                                var interfaceMap = type.GetInterfaceMap(unitInterface);
                                var mapIndex = Array.IndexOf(interfaceMap.InterfaceMethods,
                                    unitInterface.GetMethod("GetSupportedEvents"));
                                if (mapIndex >= 0)
                                    method = interfaceMap.TargetMethods[mapIndex];
                            }

                            if (method == null) continue;

                            foreach (var evt in InvokeGetSupportedEvents(type, method))
                            {
                                if (!string.IsNullOrEmpty(evt))
                                    events.Add(evt);
                            }
                        }
                        catch { }
                    }
                }
                catch { }
            }

            foreach (var assembly in allAssemblies)
            {
                try
                {
                    var soTypes = assembly.GetTypes()
                        .Where(t => t.IsClass && !t.IsAbstract && t.IsSubclassOf(typeof(SkillDataSO)));

                    foreach (var type in soTypes)
                    {
                        try
                        {
                            var instance = ScriptableObject.CreateInstance(type) as SkillDataSO;
                            if (instance?.TriggerEvents != null)
                            {
                                foreach (var evt in instance.TriggerEvents)
                                {
                                    if (!string.IsNullOrEmpty(evt))
                                        events.Add(evt);
                                }
                            }
                            UnityEngine.Object.DestroyImmediate(instance);
                        }
                        catch { }
                    }
                }
                catch { }
            }

            var guids = AssetDatabase.FindAssets("t:SkillDataSO");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var so = AssetDatabase.LoadAssetAtPath<SkillDataSO>(path);
                if (so?.TriggerEvents == null) continue;
                foreach (var evt in so.TriggerEvents)
                {
                    if (!string.IsNullOrEmpty(evt))
                        events.Add(evt);
                }
            }

            var buffGuids = AssetDatabase.FindAssets("t:BuffDataSO");
            foreach (var guid in buffGuids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var buff = AssetDatabase.LoadAssetAtPath<BuffDataSO>(path);
                if (buff?.actions == null) continue;
                foreach (var action in buff.actions)
                {
                    if (!string.IsNullOrEmpty(action?.actionName))
                        events.Add(action.actionName);
                }
            }

            events.Add("OnAttack");

            return events;
        }

        private static IEnumerable<string> InvokeGetSupportedEvents(Type type, MethodInfo method)
        {
            object instance = null;
            GameObject tempGo = null;
            try
            {
                if (typeof(MonoBehaviour).IsAssignableFrom(type))
                {
                    tempGo = EditorUtility.CreateGameObjectWithHideFlags(
                        "__TriggerEventCollect__",
                        HideFlags.HideAndDontSave,
                        type);
                    instance = tempGo.GetComponent(type);
                }
                else
                {
                    instance = Activator.CreateInstance(type);
                }

                if (method.Invoke(instance, null) is string[] eventStrings)
                    return eventStrings;
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[TriggerEventEnumGenerator] 无法从 {type.Name} 收集事件: {e.Message}");
            }
            finally
            {
                if (tempGo != null)
                    UnityEngine.Object.DestroyImmediate(tempGo);
            }

            return Array.Empty<string>();
        }

        private static List<string> ParseExistingGeneratedValues()
        {
            var generated = new List<string>();
            if (!File.Exists(ENUM_FILE_PATH)) return generated;

            var lines = File.ReadAllLines(ENUM_FILE_PATH);
            bool inGenerated = false;

            foreach (var line in lines)
            {
                if (line.Contains(GENERATED_REGION_START))
                {
                    inGenerated = true;
                    continue;
                }
                if (line.Contains(GENERATED_REGION_END))
                    break;
                if (!inGenerated) continue;

                if (SkillSystemEnumGenerator.TryParseEnumMemberLine(line, out var memberName) &&
                    SkillSystemEnumGenerator.IsValidEnumMemberName(memberName))
                {
                    generated.Add(memberName);
                }
            }

            return generated;
        }

        private static List<string> ParseExistingManualValues()
        {
            var manual = new List<string>();
            if (!File.Exists(ENUM_FILE_PATH)) return manual;

            var lines = File.ReadAllLines(ENUM_FILE_PATH);
            bool inEnum = false;

            foreach (var line in lines)
            {
                if (line.Contains("public enum TriggerEventType"))
                {
                    inEnum = true;
                    continue;
                }
                if (!inEnum) continue;
                if (line.Contains(GENERATED_REGION_START))
                    break;
                if (line.Trim() == "}")
                    break;

                if (SkillSystemEnumGenerator.TryParseEnumMemberLine(line, out var memberName) &&
                    SkillSystemEnumGenerator.IsValidEnumMemberName(memberName))
                {
                    manual.Add(memberName);
                }
            }

            return manual;
        }
    }
}
#endif
